folder_in: /home/user2/tst/file
folder_out: /home/user2/tst/out
folder_ext: /home/user2/tst/ext
folder_badarx: /home/user2/tst/badarx


count_file: 5
size_file: 1M

local_path: tests/
remote_path: /home/user2/
host: 0.0.0.0
user: user2

stat_file: /home/user2/stat.txt