folder_in: /home/axidar/PycharmProjects/AutoQA/lesson3/assem3/les/work/tst
folder_out: /home/axidar/PycharmProjects/AutoQA/lesson3/assem3/les/work/out
folder_ext: /home/axidar/PycharmProjects/AutoQA/lesson3/assem3/les/work/folder1
folder_ext2: /home/axidar/PycharmProjects/AutoQA/lesson3/assem3/les/work/folder2
count: 5
bs: 1M
